name: container actions for python

on:
  workflow_dispatch:
  push:

jobs:
  python-container:
    runs-on: ubuntu-latest
    
    steps:
      # 基本的なPythonコンテナー実行
      - name: Python バージョン確認
        uses: docker://python:3.11
        with:
          args: python --version
      
      # 簡単なPythonスクリプト実行
      - name: Hello World
        uses: docker://python:3.11
        with:
          args: python -c "print('Hello from Python container!')"
      
      # 環境変数を使用
      - name: 環境変数表示
        uses: docker://python:3.11
        env:
          MY_VAR: "テスト変数"
        with:
          args: python -c "import os; print('Repository:', os.environ.get('GITHUB_REPOSITORY')); print('Custom var:', os.environ.get('MY_VAR'))"
      
      # パッケージインストールして実行
      - name: パッケージ使用例
        uses: docker://python:3.11
        with:
          args: sh -c "pip install requests && python -c 'import requests; print(\"requests version:\", requests.__version__)'"
